package ark10;

import com.sun.org.apache.bcel.internal.generic.FLOAD;
import java.awt.LayoutManager;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.ButtonModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class NewJFrame extends javax.swing.JFrame {

    Carro carro;
    ArrayList<Carro> listaCarros = new ArrayList();

    String códico;
    String nome;
    String marca;
    String modelo;
    float preço;
    float valorDeLocação = 0;
    int diasDeLocação = 0;
    float ValorTotal;

    int c = 0;

    public NewJFrame() {
        initComponents();
        exibirValorTotal();

        this.InputTotalDaLocação.setText("0.0");
        this.InputTotalDaLocação.setEditable(false);

        this.ExibirInformaçõesNaTabela();
        this.ExibirInformaçõesParaLocação();
    }

    public void exibirValorTotal() {
        if (valorDeLocação == 0 && diasDeLocação == 0) {
            this.msgTotalLocação.setText("* Informe o Valor de Lotação e os Dias de Locação Corretamente !*");
        } else {
            this.ValorTotal = valorDeLocação * diasDeLocação;
            this.InputTotalDaLocação.setText(" " + ValorTotal);
        }
    }

    public void opComboBox() {
        jComboBox1.addItem(listaCarros.get(c).ExibirNome());
        jComboBox2.addItem(listaCarros.get(c).ExibirNome());
        c = c + 1;
    }

    public void ExibirInformaçõesNaTabela() {
        String[] colunas = new String[]{
            "Códico", "Nome", "Marca", "Modelo", "Preço", "Valor de Locação", "Dias de Locação", "Valor Total"
        };
        String[][] data = new String[listaCarros.size()][6];

        for (int i = 0; i < listaCarros.size(); i++) {
            data[i] = listaCarros.get(i).ExibirInformaçoes();

        }

        TableModel modelo = new DefaultTableModel(data, colunas);

        jTable1.setModel(modelo);
    }

    public void ExibirInformaçõesParaLocação() {
        if (this.InputC.getText().trim().equals("")) {
            String[] colunas = new String[]{
                "Códico", "Nome", "Marca", "Modelo", "Preço", "Valor de Locação", "Dias de Locação", "Valor Total"
            };
            String[][] data = new String[listaCarros.size()][6];

            for (int i = 0; i < listaCarros.size(); i++) {
                data[i] = listaCarros.get(i).ExibirInformaçoes();
            }
            TableModel modelo = new DefaultTableModel(data, colunas);
            jTable2.setModel(modelo);

        } else {
            String[] colunas = new String[]{
                "Códico", "Nome", "Marca", "Modelo", "Preço", "Valor de Locação", "Dias de Locação", "Valor Total"
            };
            String[][] data = new String[listaCarros.size()][6];

            for (int i = 0; i < listaCarros.size(); i++) {
                if (this.InputC.getText().trim().equals(listaCarros.get(i).getCódico())) {
                    data[i] = listaCarros.get(i).ExibirInformaçoes();
                }
            }
            TableModel modelo = new DefaultTableModel(data, colunas);
            jTable2.setModel(modelo);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        InputCodico = new javax.swing.JTextField();
        msgcodico = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InputNome = new javax.swing.JTextField();
        msgNome = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        InputModelo = new javax.swing.JTextField();
        msgModelo = new javax.swing.JLabel();
        msgPreço = new javax.swing.JLabel();
        InputPreço = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        msgValorDeLocação = new javax.swing.JLabel();
        InputValorDeLocação = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        msgDiasDeLocação = new javax.swing.JLabel();
        InputDiasDeLocação = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        InputTotalDaLocação = new javax.swing.JTextField();
        ADDCarros = new javax.swing.JButton();
        LimparCampos = new javax.swing.JButton();
        msgTotalLocação = new javax.swing.JLabel();
        op1 = new javax.swing.JRadioButton();
        op2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        InputC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnC = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        InputQD = new javax.swing.JTextField();
        msgDiasDeAluguel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        CM = new javax.swing.JButton();
        LimparCampos1 = new javax.swing.JButton();
        MVM = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox<>();
        MVTA = new javax.swing.JLabel();
        LimparCampos2 = new javax.swing.JButton();
        CVTA = new javax.swing.JButton();
        msgDiasDeAluguel1 = new javax.swing.JLabel();
        InputQD1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carros");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jToolBar1.setRollover(true);

        jButton1.setText("Cadastrar Carro");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton4.setText("Listar Informações");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setText("Alterar Valor de Locação");
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setText("Calcular Valor da Multa");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setText("Calcular Valor Total do Aluguel");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        jButton10.setText("Sobre");
        jButton10.setFocusable(false);
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton10);

        jButton8.setText("Sair");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton8);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel1.setText("Codico do Carro: ");

        InputCodico.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        msgcodico.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        msgcodico.setForeground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel2.setText("Nome do Carro: ");

        InputNome.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        msgNome.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        msgNome.setForeground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel3.setText("Marca do Carro: ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel4.setText("Modelo do Carro: ");

        InputModelo.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        msgModelo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        msgModelo.setForeground(new java.awt.Color(255, 0, 0));

        msgPreço.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        msgPreço.setForeground(new java.awt.Color(255, 0, 0));

        InputPreço.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel5.setText("Preço do Carro: ");

        msgValorDeLocação.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        msgValorDeLocação.setForeground(new java.awt.Color(255, 0, 0));

        InputValorDeLocação.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel6.setText("Valor de Locação : ");

        msgDiasDeLocação.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        msgDiasDeLocação.setForeground(new java.awt.Color(255, 0, 0));

        InputDiasDeLocação.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel7.setText("Dias de Locação : ");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel8.setText("Valor Total da Locação : ");

        InputTotalDaLocação.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        InputTotalDaLocação.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputTotalDaLocaçãoActionPerformed(evt);
            }
        });

        ADDCarros.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        ADDCarros.setText("Cadastrar Carro");
        ADDCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDCarrosActionPerformed(evt);
            }
        });

        LimparCampos.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        LimparCampos.setText("Limpar Todos os Campos");
        LimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCamposActionPerformed(evt);
            }
        });

        msgTotalLocação.setFont(new java.awt.Font("Times New Roman", 3, 15)); // NOI18N
        msgTotalLocação.setForeground(new java.awt.Color(255, 0, 0));

        buttonGroup1.add(op1);
        op1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        op1.setSelected(true);
        op1.setText("Sedan");

        buttonGroup1.add(op2);
        op2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        op2.setText("Fiat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(InputCodico))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(InputNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(InputPreço))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(InputDiasDeLocação))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(InputTotalDaLocação))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(InputValorDeLocação))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 210, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgcodico, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(msgNome, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(msgModelo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(msgPreço, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(LimparCampos)
                                .addGap(10, 10, 10)
                                .addComponent(ADDCarros))
                            .addComponent(msgTotalLocação, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msgValorDeLocação, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msgDiasDeLocação, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(InputModelo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(op1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(op2)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(InputCodico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgcodico)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InputNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgNome)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(op1)
                    .addComponent(op2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(InputModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgModelo)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(InputPreço, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgPreço)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(InputValorDeLocação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgValorDeLocação)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(InputDiasDeLocação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgDiasDeLocação)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(InputTotalDaLocação, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgTotalLocação)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 169, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDCarros)
                    .addComponent(LimparCampos))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastrar Carro", jPanel2);

        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jButton3.setText("Atualizar a Lista");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Listar Informações", jPanel3);

        jTable2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jTable2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable2KeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        InputC.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel9.setText("Informe o Codico do Carro");

        btnC.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        btnC.setText("Pesquisar");
        btnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jButton2.setText("Atualizar a Lista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 15)); // NOI18N
        jLabel12.setText("OBS: Após Selecionar o Carro, Pressione o Botão \"ENTER\" para Alterar o Valor de Locação, e Atualize a Lista.");

        jButton9.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jButton9.setText("Limpar Campo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 850, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(InputC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnC))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InputC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel12)
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton9))
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Alterar Valor de Locação", jPanel6);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel10.setText("Informe a Quantidades de Dias que o Carro ficou Alugado :  ");

        InputQD.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        msgDiasDeAluguel.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        msgDiasDeAluguel.setForeground(new java.awt.Color(255, 0, 0));

        CM.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        CM.setText("Calcular Multa");
        CM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMActionPerformed(evt);
            }
        });

        LimparCampos1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        LimparCampos1.setText("Limpar Todos os Campos");
        LimparCampos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCampos1ActionPerformed(evt);
            }
        });

        MVM.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msgDiasDeAluguel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MVM, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(InputQD, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LimparCampos1)
                        .addGap(10, 10, 10)
                        .addComponent(CM)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(InputQD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgDiasDeAluguel)
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CM)
                    .addComponent(LimparCampos1))
                .addGap(18, 18, 18)
                .addComponent(MVM)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calculara Valor da Multa", jPanel4);

        MVTA.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        LimparCampos2.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        LimparCampos2.setText("Limpar Todos os Campos");
        LimparCampos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimparCampos2ActionPerformed(evt);
            }
        });

        CVTA.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        CVTA.setText("Calcular Valor Total do Aluguel");
        CVTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVTAActionPerformed(evt);
            }
        });

        msgDiasDeAluguel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        msgDiasDeAluguel1.setForeground(new java.awt.Color(255, 0, 0));

        InputQD1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jLabel11.setText("Informe a Quantidades de Dias que o Carro ficou Alugado :  ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(msgDiasDeAluguel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MVTA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(InputQD1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LimparCampos2)
                        .addGap(10, 10, 10)
                        .addComponent(CVTA)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(InputQD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgDiasDeAluguel1)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CVTA)
                    .addComponent(LimparCampos2))
                .addGap(18, 18, 18)
                .addComponent(MVTA)
                .addContainerGap(443, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Calcular Valor Total do Aluguel", jPanel5);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.jTabbedPane1.setSelectedComponent(this.jPanel2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ADDCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDCarrosActionPerformed
        msgcodico.setText("");
        msgNome.setText("");
        msgModelo.setText("");
        msgPreço.setText("");
        msgValorDeLocação.setText("");
        msgDiasDeLocação.setText("");

        try {
            this.códico = this.InputCodico.getText().trim();
            this.nome = this.InputNome.getText().trim();
            this.modelo = this.InputModelo.getText().trim();
            this.preço = Float.parseFloat(this.InputPreço.getText().trim());
            this.valorDeLocação = Float.parseFloat(this.InputValorDeLocação.getText().trim());
            this.diasDeLocação = Integer.parseInt(this.InputDiasDeLocação.getText().trim());

            if (this.op1.isSelected()) {
                this.marca = "Sedan";
            }
            if (this.op2.isSelected()) {
                this.marca = "Fiat";
            }
            exibirValorTotal();

            this.InputCodico.setText("");
            this.InputNome.setText("");
            this.InputModelo.setText("");
            this.InputPreço.setText("");
            this.InputValorDeLocação.setText("");
            this.InputDiasDeLocação.setText("");
            this.InputTotalDaLocação.setText("0.0");

            carro = new Carro(códico, nome, marca, modelo, preço, valorDeLocação, diasDeLocação, ValorTotal);
            listaCarros.add(carro);

            this.ExibirInformaçõesNaTabela();
            this.ExibirInformaçõesParaLocação();
            this.opComboBox();

        } catch (Exception e) {
            if (this.InputCodico.getText().trim().equals("")) {
                msgcodico.setText("* Informe um Codico parra o Carro !*");
            }
            if (this.InputNome.getText().trim().equals("")) {
                msgNome.setText("* Informe um Nome para o Carro !*");
            }
            if (this.InputModelo.getText().trim().equals("")) {
                msgModelo.setText("* Informe um Modelo para o Carro !*");
            }
            msgPreço.setText("* Informe um Preço para o Carro, Só Serão Aceitos Valores Numericos nesse Campo !*");
            msgValorDeLocação.setText("* Informe o Valor de Locação para o Carro, Só Serão Aceitos Valores Numericos nesse Campo !*");
            msgDiasDeLocação.setText("* Informe a Quantidades de Dias de Locação do Carro, Só Serão Aceitos Valores Numericos nesse Campo !*");

        }

    }//GEN-LAST:event_ADDCarrosActionPerformed

    private void LimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCamposActionPerformed
        this.InputCodico.setText("");
        this.InputNome.setText("");
        this.InputModelo.setText("");
        this.InputPreço.setText("");
        this.InputValorDeLocação.setText("");
        this.InputDiasDeLocação.setText("");
        this.InputTotalDaLocação.setText("0.0");

        msgcodico.setText("");
        msgNome.setText("");
        msgModelo.setText("");
        msgPreço.setText("");
        msgValorDeLocação.setText("");
        msgDiasDeLocação.setText("");
    }//GEN-LAST:event_LimparCamposActionPerformed

    private void InputTotalDaLocaçãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputTotalDaLocaçãoActionPerformed

    }//GEN-LAST:event_InputTotalDaLocaçãoActionPerformed

    private void CMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMActionPerformed
        msgDiasDeAluguel.setText("");
        try {
            int ax = jComboBox1.getSelectedIndex();
            int ax2 = listaCarros.get(ax).getDiasDeLocação();
            float ax3 = listaCarros.get(ax).getValorDeLocação();
            String ax4 = (String) jComboBox1.getSelectedItem();
            int ax1 = Integer.parseInt(this.InputQD.getText().trim());

            float valorMulta = carro.CalcularValorMulta(ax1, ax2, ax3);

            this.MVM.setText("O Valor da Multa Pertencente ao Carro: " + ax4 + " é: " + valorMulta + " Reais.");
            this.msgDiasDeAluguel.setText("");
        } catch (Exception e) {
            this.msgDiasDeAluguel.setText("* Informe a Quantidades de Dias Totais que o Carro Ficou Álugado, Só Serão Aceitos Valores Numericos nesse Campo !*");
        }
    }//GEN-LAST:event_CMActionPerformed

    private void LimparCampos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCampos1ActionPerformed
        this.MVM.setText("");
        this.msgDiasDeAluguel.setText("");
    }//GEN-LAST:event_LimparCampos1ActionPerformed

    private void LimparCampos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimparCampos2ActionPerformed
        this.MVTA.setText("");
        this.msgDiasDeAluguel1.setText("");
    }//GEN-LAST:event_LimparCampos2ActionPerformed

    private void CVTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVTAActionPerformed
        msgDiasDeAluguel1.setText("");
        try {
            int ax = jComboBox2.getSelectedIndex();
            int ax2 = listaCarros.get(ax).getDiasDeLocação();
            float ax3 = listaCarros.get(ax).getValorDeLocação();
            String ax4 = (String) jComboBox1.getSelectedItem();
            int ax1 = Integer.parseInt(this.InputQD1.getText().trim());

            float valorTotal = carro.CalcularValorToltal(ax1, ax2, ax3);

            this.MVTA.setText("O Valor Total do Aluguel Pertencente ao Carro: " + ax4 + " é: " + valorTotal + " Reais.");
            this.msgDiasDeAluguel1.setText("");
        } catch (Exception e) {
            this.msgDiasDeAluguel1.setText("* Informe a Quantidades de Dias Totais que o Carro Ficou Álugado, Só Serão Aceitos Valores Numericos nesse Campo !*");
        }
    }//GEN-LAST:event_CVTAActionPerformed

    private void btnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCActionPerformed
        this.ExibirInformaçõesParaLocação();
    }//GEN-LAST:event_btnCActionPerformed

    private void jTable2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            int id = jTable2.getSelectedRow();
            NewJFrame1 newJFrame1 = new NewJFrame1(listaCarros, id);
            newJFrame1.setVisible(true);
        }
    }//GEN-LAST:event_jTable2KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.ExibirInformaçõesParaLocação();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.ExibirInformaçõesNaTabela();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jTabbedPane1.setSelectedComponent(this.jPanel3);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.jTabbedPane1.setSelectedComponent(this.jPanel6);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.jTabbedPane1.setSelectedComponent(this.jPanel4);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.jTabbedPane1.setSelectedComponent(this.jPanel5);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        this.InputC.setText("");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      Sobre sobre = new Sobre();
        sobre.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed
   
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDCarros;
    private javax.swing.JButton CM;
    private javax.swing.JButton CVTA;
    private javax.swing.JTextField InputC;
    private javax.swing.JTextField InputCodico;
    private javax.swing.JTextField InputDiasDeLocação;
    private javax.swing.JTextField InputModelo;
    private javax.swing.JTextField InputNome;
    private javax.swing.JTextField InputPreço;
    private javax.swing.JTextField InputQD;
    private javax.swing.JTextField InputQD1;
    private javax.swing.JTextField InputTotalDaLocação;
    private javax.swing.JTextField InputValorDeLocação;
    private javax.swing.JButton LimparCampos;
    private javax.swing.JButton LimparCampos1;
    private javax.swing.JButton LimparCampos2;
    private javax.swing.JLabel MVM;
    private javax.swing.JLabel MVTA;
    private javax.swing.JButton btnC;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel msgDiasDeAluguel;
    private javax.swing.JLabel msgDiasDeAluguel1;
    private javax.swing.JLabel msgDiasDeLocação;
    private javax.swing.JLabel msgModelo;
    private javax.swing.JLabel msgNome;
    private javax.swing.JLabel msgPreço;
    private javax.swing.JLabel msgTotalLocação;
    private javax.swing.JLabel msgValorDeLocação;
    private javax.swing.JLabel msgcodico;
    private javax.swing.JRadioButton op1;
    private javax.swing.JRadioButton op2;
    // End of variables declaration//GEN-END:variables
}
